services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:80"
    container_name: spring-payments
    environment:
      SPRING_PROFILES_ACTIVE: default
    restart: unless-stopped
